---
- name: Install Freepbx
  hosts: all
  become: true
  tasks:
    - name: Transfer the script
      copy:
        src: install_asterisk_freepbx.sh
        dest: /tmp
        mode: '0777'

    - name: Change permission of file
      file:
        path: /tmp/install_asterisk_freepbx.sh
        mode: '+x'
      register: file_permission_changed

    - name: Install Screen
      become: yes
      package:
        name: screen
        state: present

    - name: Enable logging for a screen session
      command: |
        screen -L -dmS mysession -Logfile /var/log/install_freepbx.txt

    - name: Run pre-install script
      command: sh -c "screen -S mysession -X stuff '/tmp/install_asterisk_freepbx.sh\n'"

    - name: Debug screen session
      debug:
        msg: "Screen session with name mysession is being logged on and output is being redirected to a file. To trace the progress, consult /var/log/install_freepbx.txt."

