---
- name: Install FreePBX with Asterisk
  hosts: all
  become: yes

  tasks:
    - name: Import MongoDB GPG key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-5.0.asc
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/debian {{ ansible_lsb.codename }}/mongodb-org/5.0 main"
        state: present

    - name: Update OS
      apt:
        update_cache: 'yes'
        upgrade: 'yes'

    - name: Install necessary packages
      apt:
        name:
          - util-linux
          - apache2
          - mariadb-server
          - mariadb-client
          - php
          - php-curl
          - php-cli
          - php-pdo
          - php-mysql
          - php-pear
          - php-gd
          - php-mbstring
          - php-intl
          - php-bcmath
          - curl
          - sox
          - mpg123
          - lame
          - ffmpeg
          - sqlite3
          - git
          - unixodbc
          - sudo
          - dirmngr
          - postfix
          - asterisk
          - odbc-mariadb
          - php-ldap
          - nodejs
          - npm
          - pkg-config
          - libicu-dev
          - mongodb-org
          - mongodb-org-server
          - mongodb-org-shell
          - mongodb-org-mongos
          - mongodb-org-tools
        state: present
        update_cache: yes
      register: packages_result

    - name: Prepare Asterisk
      shell: |
        systemctl stop asterisk
        systemctl disable asterisk
        cd /etc/asterisk
        mkdir DIST
        mv * DIST
        cp DIST/asterisk.conf .
        sed -i 's/(!)//' asterisk.conf
      args:
        creates: /etc/asterisk/modules.conf
      changed_when: false

    - name: Configure Apache web server
      lineinfile:
        path: /etc/php/7.4/apache2/php.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^(upload_max_filesize = ).*", line: "upload_max_filesize = 20M" }
        - { regexp: "^(memory_limit = ).*", line: "memory_limit = 256M" }
      notify:
        - restart apache2

    - name: Configure ODBC
      copy:
        dest: "{{ item.dest }}"
        content: "{{ item.content }}"
      with_items:
        - dest: "/etc/odbcinst.ini"
          content: |
            [MySQL]
            Description = ODBC for MySQL (MariaDB)
            Driver = /usr/lib/x86_64-linux-gnu/odbc/libmaodbc.so
            FileUsage = 1
        - dest: "/etc/odbc.ini"
          content: |
            [MySQL-asteriskcdrdb]
            Description = MySQL connection to 'asteriskcdrdb' database
            Driver = MySQL
            Server = localhost
            Database = asteriskcdrdb
            Port = 3306
            Socket = /var/run/mysqld/mysqld.sock
            Option = 3

    - name: Remove any previous FreePBX installation
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/src/freepbx
        - /var/www/html/admin/modules/xmpp/node/node_modules/freepbx



    - name: Download FreePBX package
      get_url:
        url: http://mirror.freepbx.org/modules/packages/freepbx/7.4/freepbx-16.0-latest.tgz
        dest: /usr/local/src/freepbx-16.0-latest.tgz

    - name: Extract FreePBX package
      become: true
      unarchive:
        src: /usr/local/src/freepbx-16.0-latest.tgz
        dest: /usr/local/src/
        copy: false

    - name: Start Asterisk
      command: /usr/local/src/freepbx/start_asterisk start

    - name: Install FreePBX
      command: /usr/local/src/freepbx/install -n
      args:
        chdir: /usr/local/src/freepbx/
      register: freepbx_install_result

    - name: Check if FreePBX installation was successful
      set_fact:
        freepbx_installed: "{{ freepbx_install_result.stdout_lines | regex_search('FreePBX successfully installed') }}"
      when: freepbx_install_result is succeeded

    - name: Print installation status
      debug:
        msg: "FreePBX installation status: {{ 'successful' if freepbx_installed else 'failed' }}"

    - name: Add MongoDB repository
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/5.0 main"
        state: present
        update_cache: yes

    - name: Install MongoDB package
      apt:
        name: mongodb-org
        state: present

    - name: Disable commercial repository
      command: fwconsole ma disablerepo commercial

    - name: Install all FreePBX modules
      command: fwconsole ma installall

    - name: Delete the firewall module
      command: fwconsole ma delete firewall

    - name: Apply current FreePBX configuration
      command: fwconsole reload
    
    - name: Create directory and rename existing directory
      become: yes
      file:
        path: /usr/share/asterisk
        state: directory
        recurse: yes
        backup: yes
        force: yes

    - name: move default sound directory
      become: yes
      command:
        cmd: |
          mv /usr/share/asterisk/sounds /usr/share/asterisk/sounds-DIST

    - name: Set symlink to correct sound files
      become: yes
      file:
        src: /var/lib/asterisk/sounds
        dest: /usr/share/asterisk/sounds
        state: link
        force: yes

    - name: Restart to load Asterisk modules
      command: fwconsole restart

    - name: Set up systemd
      copy:
        content: |
          [Unit]
          Description=FreePBX VoIP Server
          After=mariadb.service

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/usr/sbin/fwconsole start -q
          ExecStop=/usr/sbin/fwconsole stop -q

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/freepbx.service 
        mode: '0644'     

    - name: Enable FreePBX systemd service
      systemd:
        name: freepbx
        enabled: yes
      notify: restart freepbx

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

    - name: restart freepbx
      systemd:
        name: freepbx
        state: restarted

