---
- name: Monitor file in real-time
  hosts: all
  gather_facts: no
  tasks:
    - name: Run "tail" command on file
      command: tail -f /tmp/install_fusionpbx.txt
      register: tail_output
      async: 1
      poll: 0

    - name: Print real-time updates of the file
      debug:
        var: tail_output.stdout_lines
      delay: 10

