---
- name: Set VGA mode to 800x600
  hosts: all
  become: yes
  
  tasks:
    - name: Set GRUB_CMDLINE_LINUX_DEFAULT
      lineinfile:
        dest: /etc/default/grub
        line: GRUB_CMDLINE_LINUX_DEFAULT="quiet vga=800"
        state: present
        backrefs: yes
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='

    - name: Update GRUB configuration
      command: update-grub
      become: yes
