---
- name: Set VGA mode to 800x600
  hosts: all
  become: yes

  tasks:
    - name: Set GRUB_CMDLINE_LINUX_DEFAULT
      lineinfile:
        dest: /etc/default/grub
        line: GRUB_CMDLINE_LINUX_DEFAULT="quiet vga=800"
        state: present
        backrefs: yes
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='

    - name: Update GRUB configuration
      command: update-grub
      become: yes

    - name: Create gateway_settings service file
      copy:
        dest: /etc/systemd/system/gateway_settings.service
        content: |
          [Unit]
          Description=Gateway settings
          After=network.target
          Wants=network.target

          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/dhclient -v
          RemainAfterExit=no

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd

    - name: Enable and start network_up service
      systemd:
        name: gateway_settings.service
        enabled: yes
        state: started

    - name: Create network_up.sh script
      copy:
        content: |
          #!/bin/bash
          for interface in $(ip link | awk -F': ' '{print $2}' | grep -v '^lo$'); do
              ip link set $interface up
          done
        dest: /usr/local/bin/network_up.sh
        mode: '0755'

    - name: Create network_up.service file
      copy:
        content: |
          [Unit]
          Description=Set all Ethernet interfaces up
          After=network-online.target

          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/network_up.sh

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/network_up.service
        mode: '0644'

    - name: Enable and start network_up service
      systemd:
        name: network_up.service
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

