---
- name: Install and Configure Zerotier
  hosts: all
  become: yes
  
  tasks:
    - name: Install curl, sudo, and openssh-server
      apt:
        name:
          - curl
          - sudo
          - openssh-server
        state: present
        
    - name: Download Zerotier
      command: curl -s https://install.zerotier.com | sudo bash

    - name: Join Zerotier network
      command: zerotier-cli join 8bd5124fd642e41c
      
    - name: Change allowManaged setting
      command: zerotier-cli set 8bd5124fd642e41c allowManaged=0
