---
- name: Install Zerotier
  hosts: all
  become: true
  tasks:
  - name: Download Zerotier installation script
    get_url:
      url: https://install.zerotier.com
      dest: /tmp/zerotier_install.sh
  - name: Install Zerotier
    shell: bash /tmp/zerotier_install.sh
    args:
      creates: /usr/sbin/zerotier-one

