---
- name: Create OVS Bridges
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install openvswitch-switch and net-tools
      become: true
      apt:
        name: [openvswitch-switch, net-tools]
        state: present

    - name: Enable and start openvswitch-switch service
      become: true
      service:
        name: openvswitch-switch
        state: started
        enabled: yes

    - name: Create the first OVS bridge
      become: true
      shell: |
        ovs-vsctl add-br br0
        ovs-vsctl add-port br0 eth1
        ovs-vsctl add-port br0 eth2
        ovs-vsctl add-port br0 zt
        ovs-vsctl set port eth1 tag=10
        ovs-vsctl set port eth2 tag=10

    - name: Create the second OVS bridge
      become: true
      shell: |
        ovs-vsctl add-br br1
        ovs-vsctl add-port br1 eth0
        ovs-vsctl add-port br1 zt
