---
- name: Create OVS bridge between ZT and all other interfaces
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Detect zerotier network name
    command: zerotier-cli listnetworks
    register: zt_networks

  - name: Get all other network interfaces
    command: ip addr | grep '^[0-9]:' | awk '{print $2}' | awk -F: '{print $1}' | grep '.*[0-9]$'
    register: all_interfaces

  - name: Create OVS bridge
    command: ovs-vsctl add-br br0 && ovs-vsctl add-port br0 {{ item }}
    with_items: "{{ all_interfaces.stdout_lines }}"
    when: "'zt' in item or item in zt_networks.stdout_lines"

