---
- name: Transfer and execute a script.
  hosts: all
  remote_user: root
  tasks:
     - name: Transfer the script
       copy: src=find_network_interfaces_same_pci.sh dest=/tmp mode=0777

     - name: Run similar names script
       command: "/tmp/find_network_interfaces_same_pci.sh"
       register: network_interface_list

     - name: Process network interfaces
       set_fact:
         network_interfaces: "{{ network_interface_list.stdout_lines }}"

     - name: Loop over network interfaces
       debug:
         msg: "Processing network interface: {{ item }}"
       loop: "{{ network_interfaces }}"
       loop_control:
         loop_var: item

     - name: Remove the shell script
       file:
         path: /tmp/find_network_interfaces_same_pci.sh
         state: absent

     - name: Create OVS bridge and add interfaces
       shell: ovs-vsctl add-br br0 && ovs-vsctl add-port br0 {{ item }}
       with_items: "{{ network_interfaces }}"

     - name: Add interfaces to bridge
       command: "ovs-vsctl add-port br0 {{ item }}"
       with_items: "{{ network_interface_list.stdout_lines }}"
