---
- name: Firewall Adjustment Script
  hosts: all
  remote_user: root

  tasks:
    - name: Uncomment sysctl.conf lines needed for router and forward traffic
      become: true
      become_method: sudo
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^# {{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - { regexp: 'net.ipv4.conf.all.accept_source_route', line: 'net.ipv4.conf.all.accept_source_route = 0' }
        - { regexp: 'net.ipv4.conf.all.send_redirects', line: 'net.ipv4.conf.all.send_redirects = 0' }
        - { regexp: 'net.ipv4.ip_forward', line: 'net.ipv4.ip_forward = 1' }

    - name: run the packet forwarder
      become_method: sudo
      become_user: root
      command: sysctl -w net.ipv4.ip_forward=1

