---
- name: Firewall Adjustment Script
  hosts: all
  remote_user: root
  vars:
    zones:
      - trusted
      - internal_no_internet
      - internal_internet
  tasks:
    - name: Transfer find network script
      copy:
        src: find_network_interfaces_same_pci.sh
        dest: /tmp
        mode: 0777

    - name: Transfer the firewall connection script
      copy:
        src: connect_ethernet_interfaces_to_zones.sh
        dest: /tmp
        mode: 0777

    - name: Install firewalld
      become: yes
      package:
        name: firewalld
        state: present

    - name: Start firewalld service
      become: yes
      service:
        name: firewalld
        state: started

    - name: Set default zone as public
      become: yes
      command: firewall-cmd --set-default-zone=public

    - name: Enable masquerade in the public zone
      become: yes
      command: firewall-cmd --zone=public --add-masquerade

    - name: Create missing zones
      become: true
      command: firewall-cmd --permanent --get-zones
      register: firewall_zones
      changed_when: false

    - name: Create trusted zone
      become: true
      command: firewall-cmd --permanent --new-zone=trusted
      when: "'trusted' not in firewall_zones.stdout_lines[0].split(' ')"
      changed_when: true

    - name: Create internal_internet zone
      become: true
      command: firewall-cmd --permanent --new-zone=internalNet
      when: "'internalNet' not in firewall_zones.stdout_lines[0].split(' ')"
      changed_when: true

    - name: Create internal_no_internet zone
      become: true
      command: firewall-cmd --permanent --new-zone=internalNoNet
      when: "'internalNoNet' not in firewall_zones.stdout_lines[0].split(' ')"
      changed_when: true

    - name: Create Zerotier zone
      become: true
      command: firewall-cmd --permanent --new-zone=zerotier
      when: "'zerotier' not in firewall_zones.stdout_lines[0].split(' ')"
      changed_when: true

    - name: Run Firewall and zones script to add each port to its zone
      command: "/tmp/connect_ethernet_interfaces_to_zones.sh {{ zerotier_ip_range }}"
      register: network_interface_list

    - name: Allow full duplex communication between the internal_with_internet and zerotier zones
      become: yes
      command: firewall-cmd --permanent --zone=internalNet --add-source={{ zerotier_ip_range }}/24
      command: firewall-cmd --permanent --zone=zerotier --add-source-zone=internalNet

    - name: Allow full duplex communication between the internal_no_internet and internal_with_internet zones
      become: yes
      command: firewall-cmd --permanent --zone=internalNoNet --add-source-zone=internalNet
      command: firewall-cmd --permanent --zone=internalNet --add-source-zone=internalNoNet

    - name: Allow zerotier zone to access the internet
      become: yes
      command: firewall-cmd --zone=zerotier --add-forward-port=port=0-65535:proto=tcp:toport=0-65535
      command: firewall-cmd --zone=zerotier --add-forward-port=port=0-65535:proto=udp:toport=0-65535

    - name: Make the changes permanent
      become: yes
      command: firewall-cmd --runtime-to-permanent

    - name: Reload the firewall
      become: yes
      command: firewall-cmd --reload
