---
- name: Firewall Adjustment Script
  hosts: all
  remote_user: root
  vars:
  tasks:
    - name: Transfer find network script
      copy:
        src: find_network_interfaces_same_pci.sh
        dest: /tmp
        mode: 0777

    - name: Transfer the firewall connection script
      copy:
        src: connect_ethernet_interfaces_to_zones.sh
        dest: /tmp
        mode: 0777

    - name: Install firewalld
      become: yes
      package:
        name: firewalld
        state: present

    - name: Start firewalld service
      become: yes
      service:
        name: firewalld
        state: started

    - name: Set default zone as public
      become: yes
      command: firewall-cmd --set-default-zone=public

    - name: Enable masquerade in the public zone
      become: yes
      command: firewall-cmd --zone=public --add-masquerade

    - name: Create the trusted zone
      become: yes
      command: firewall-cmd --permanent --new-zone=trusted

    - name: Create the internal_with_internet zone
      become: yes
      command: firewall-cmd --permanent --new-zone=internal_with_internet

    - name: Create the internal_no_internet zone
      become: yes
      command: firewall-cmd --permanent --new-zone=internal_no_internet

    - name: Run Firewall and zones script
      command: "/tmp/connect_ethernet_interfaces_to_zones.sh {{ zerotier_ip_range }}"
      register: network_interface_list

    - name: Allow full duplex communication between the internal_with_internet and zerotier zones
      become: yes
      command: firewall-cmd --permanent --zone=internal_with_internet --add-source=zerotier
      command: firewall-cmd --permanent --zone=zerotier --add-source=internal_with_internet

    - name: Allow full duplex communication between the internal_no_internet and internal_with_internet zones
      become: yes
      command: firewall-cmd --permanent --zone=internal_no_internet --add-source=internal_with_internet
      command: firewall-cmd --permanent --zone=internal_with_internet --add-source=internal_no_internet

    - name: Allow zerotier zone to access the internet
      become: yes
      command: firewall-cmd --zone=zerotier --add-forward-port=port=0-65535:proto=tcp:toport=0-65535
      command: firewall-cmd --zone=zerotier --add-forward-port=port=0-65535:proto=udp:toport=0-65535

    - name: Make the changes permanent
      become: yes
      command: firewall-cmd --runtime-to-permanent

    - name: Reload the firewall
      become: yes
      command: firewall-cmd --reload

