- name: Install FreePBX with Asterisk
  hosts: all
  become: yes

  tasks:
    - name: Update OS
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install necessary packages
      apt:
        name:
          - util-linux
          - apache2
          - mariadb-server
          - mariadb-client
          - php
          - php-curl
          - php-cli
          - php-pdo
          - php-mysql
          - php-pear
          - php-gd
          - php-mbstring
          - php-intl
          - php-bcmath
          - curl
          - sox
          - mpg123
          - lame
          - ffmpeg
          - sqlite3
          - git
          - unixodbc
          - sudo
          - dirmngr
          - postfix
          - asterisk
          - odbc-mariadb
          - php-ldap
          - nodejs
          - npm
          - pkg-config
          - libicu-dev
		  - mongodb-org
		  - mongodb-org-server
          - mongodb-org-shell
		  - mongodb-org-mongos
		  - mongodb-org-tools
        state: present
        update_cache: yes
      register: packages_result

    - name: Prepare Asterisk
      shell: |
        systemctl stop asterisk
        systemctl disable asterisk
        cd /etc/asterisk
        mkdir DIST
        mv * DIST
        cp DIST/asterisk.conf .
        sed -i 's/(!)//' asterisk.conf
        touch modules.conf
        touch cdr.conf

    - name: Configure Apache web server
      become: yes
      lineinfile:
        path: /etc/php/7.4/apache2/php.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^(upload_max_filesize = ).*", line: "upload_max_filesize = 20M" }
        - { regexp: "^(memory_limit = ).*", line: "memory_limit = 256M" }
      lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^(User|Group).*$", line: "User asterisk" }
        - { regexp: "^AllowOverride None$", line: "AllowOverride All" }
      service:
        name: apache2
        state: restarted
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Configure ODBC
      become: yes
      copy:
        dest: "{{ item.dest }}"
        content: "{{ item.content }}"
      with_items:
        - { dest: "/etc/odbcinst.ini", content: |
            [MySQL]
            Description = ODBC for MySQL (MariaDB)
            Driver = /usr/lib/x86_64-linux-gnu/odbc/libmaodbc.so
            FileUsage = 1
          }
        - { dest: "/etc/odbc.ini", content: |
            [MySQL-asteriskcdrdb]
            Description = MySQL connection to 'asteriskcdrdb' database
            Driver = MySQL
            Server = localhost
            Database = asteriskcdrdb
            Port = 3306
            Socket = /var/run/mysqld/mysqld.sock
            Option = 3
          }

    - name: Download FreePBX package
      get_url:
        url: http://mirror.freepbx.org/modules/packages/freepbx/7.4/freepbx-16.0-latest.tgz
        dest: /usr/local/src/freepbx-16.0-latest.tgz

    - name: Extract FreePBX package
      become: true
      unarchive:
        src: /usr/local/src/freepbx-16.0-latest.tgz
        dest: /usr/local/src/
        remote_src: true
        copy: no

    - name: Start Asterisk
      command: /usr/local/src/freepbx/start_asterisk start

    - name: Install FreePBX
      command: /usr/local/src/freepbx/install -n
      args:
        chdir: /usr/local/src/freepbx/

	- name: Install MongoDB from vendor's repo to enable xmpp module 
	  apt:
		name: mongodb-org
		state: present
		enablerepo: mongodb-org-{{mongodb_version.major}}
		vars:
		  mongodb_version:
			major: 4.4
			minor: 0
			patch: 0

    - name: Disable commercial repository
      command: fwconsole ma disablerepo commercial

    - name: Install all FreePBX modules
      command: fwconsole ma installall

    - name: Delete the firewall module
      command: fwconsole ma delete firewall
	  
	- name: Apply current FreePBX configuration
	  command: fwconsole reload

	- name: Set symlinks to correct sound files
	  command: >
		cd /usr/share/asterisk && 
		mv sounds sounds-DIST && 
		ln -s /var/lib/asterisk/sounds sounds

	- name: Restart to load Asterisk modules
	  command: fwconsole restart

	- name: Set up systemd
	  blockinfile:
		path: /etc/systemd/system/freepbx.service
		block: |
		  [Unit]
		  Description=FreePBX VoIP Server
		  After=mariadb.service
		  [Service]
		  Type=oneshot
		  RemainAfterExit=yes
		  ExecStart=/usr/sbin/fwconsole start -q
		  ExecStop=/usr/sbin/fwconsole stop -q
		  [Install]
		  WantedBy=multi-user.target
	  notify: restart freepbx

	- name: Enable FreePBX systemd service
	  systemd:
		name: freepbx
		enabled: yes
	  notify: restart freepbx

	handlers:
	- name: restart freepbx
	  systemd:
		name: freepbx
		state: restarted
