---
- name: Install FusionPBX
  hosts: all
  become: true
  tasks:
    - name: Download pre-install script
      get_url:
        url: https://raw.githubusercontent.com/fusionpbx/fusionpbx-install.sh/master/debian/pre-install.sh
        dest: /tmp/pre-install.sh
      register: result

    - name: Change permission of file
      file:
        path: /tmp/pre-install.sh
        mode: '+x'
      register: file_permission_changed

    - name: Install Screen
      become: yes
      package:
        name: screen
        state: present

    - name: Enable logging for a screen session
      command: |
        screen -L -dmS mysession -Logfile /tmp/install_fusionpbx.txt

    - name: Run pre-install script
      command: sh -c "screen -S mysession -X stuff '/tmp/pre-install.sh\n'"

    - name: Edit config.sh file
      lineinfile:
        dest: /usr/src/fusionpbx-install.sh/debian/resources/config.sh
        line: "{{ item.line }}"
        state: present
      with_items:
        - { line: 'domain_name={{ domain_name | default("127.0.0.1") }}' }
        - { line: 'system_username={{ system_username | default("admin") }}' }
        - { line: 'system_password={{ system_password | default(lookup("password", password_length=32, chars="ascii_letters+digits")) }}' }
        - { line: 'database_name={{ database_name | default("fusionpbx") }}' }
        - { line: 'database_username={{ database_username | default("fusionpbx") }}' }
        - { line: 'database_password={{ database_password | default(lookup("password", password_length=32, chars="ascii_letters+digits")) }}' }
        - { line: 'database_repo={{ database_repo | default("system") }}' }
        - { line: 'database_host={{ database_host | default("127.0.0.1") }}' }
        - { line: 'database_port={{ database_port | default("5432") }}' }
        - { line: 'letsencrypt_folder={{ letsencrypt_folder | default("true") }}' }


    - name: Install Fusion PBX using screen
      command: sh -c "screen -S mysession -X stuff 'cd /usr/src/fusionpbx-install.sh/debian && ./install.sh\n'"
      register: fusion_pbx_install

    - name: Debug screen session
      debug:
        msg: "Screen session with name mysession is being logged on and output is being redirected to a file. To trace the progress, connect from another shell, and type tail -f /tmp/install_fusionpbx.txt"

