---
- name: Install FusionPBX
  hosts: all
  become: true
  tasks:
    - name: Download pre-install script
      get_url:
        url: https://raw.githubusercontent.com/fusionpbx/fusionpbx-install.sh/master/debian/pre-install.sh
        dest: /tmp/pre-install.sh
      register: result

    - name: Run pre-install script
      command: sh /tmp/pre-install.sh
      when: result.changed

    - name: Edit config.sh file
      lineinfile:
        dest: /usr/src/fusionpbx-install.sh/debian/resources/config.sh
        line: "{{ item.line }}"
        state: present
      with_items:
        - { line: 'domain_name={{ domain_name | default("127.0.0.1") }}' }
        - { line: 'system_username={{ system_username | default("admin") }}' }
        - { line: 'system_password={{ system_password | default(lookup("password", password_length=32, chars="ascii_letters+digits")) }}' }
        - { line: 'database_name={{ database_name | default("fusionpbx") }}' }
        - { line: 'database_username={{ database_username | default("fusionpbx") }}' }
        - { line: 'database_password={{ database_password | default(lookup("password", password_length=32, chars="ascii_letters+digits")) }}' }
        - { line: 'database_repo={{ database_repo | default("system") }}' }
        - { line: 'database_host={{ database_host | default("127.0.0.1") }}' }
        - { line: 'database_port={{ database_port | default("5432") }}' }
        - { line: 'letsencrypt_folder={{ letsencrypt_folder | default("true") }}' }

    - name: Install Screen
      become: yes
      package:
        name: screen
        state: present

    - name: Create a new screen session
      command: screen -d -m
      register: screen_session

    - name: Get screen session ID
      shell: screen -ls | awk -F"." '/[0-9]*\s*\(Detached\)/ {print $1}' | tail -1
      register: screen_session_id
      when: screen_session is changed

    - name: Print screen session ID
      debug:
       var: screen_session_id.stdout_lines
      when: screen_session is changed

    - name: Create a new screen session
      command: screen -r {{ screen_session_id }} -X log on
      become: true

    - name: Enable logging for a screen session
      command: screen -r {{ screen_session_id }} -X logfile /tmp/install_fusionpbx.txt
      args:
        creates: /tmp/install_fusionpbx.txt

    - name: Install Fusion PBX using screen
      command: sh -c "screen -S screen_session -d -m ./install.sh"
      args:
        chdir: /usr/src/fusionpbx-install.sh/debian
      register: fusion_pbx_install

    - name: Debug screen session
      debug:
        msg: "Screen session with ID {{ screen_session_id }} is being logged on and output is being redirected to a fiile. To trace the progress, connect from another shell, and type tail -d /tmp/install_fusionpbx.txt  "
